# Generated by Django 3.1.6 on 2021-03-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='info',
            field=models.CharField(default='', max_length=128),
        ),
    ]
